<a href="https://colab.research.google.com/github/hvu88/Programacion_101/blob/Parte2/Examen_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Pregunta 1
Crea un array unidimensional que contenga los números primos entre 1 y 50

In [2]:
array_unidimensional = np.array([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47])
array_unidimensional

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de filas. Si es necesario, agrega ceros al final del
array para completar la matriz.

In [7]:
if len(array_unidimensional) % 2 != 0:
  array_unidimensional = np.append(array_unidimensional, 0)

matriz = array_unidimensional.reshape(-1,2)
matriz

array([[ 2,  3],
       [ 5,  7],
       [11, 13],
       [17, 19],
       [23, 29],
       [31, 37],
       [41, 43],
       [47,  0]])

Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [8]:
suma_filas = np.sum(matriz, axis=1)
suma_filas

array([ 5, 12, 24, 36, 52, 68, 84, 47])

#Pregunta 2
Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100

In [9]:
array_bidimensional = np.random.randint(1, 101, size=(4, 4))
array_bidimensional

array([[37, 33, 93, 89],
       [33, 23, 54, 40],
       [46, 95, 58, 47],
       [62, 14, 74, 14]])

 Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.

In [11]:
array_bidimensional = array_bidimensional.astype(np.float64)
array_bidimensional = array_bidimensional / 3.7
array_bidimensional


array([[2.7027027 , 2.41051863, 6.79327977, 6.50109569],
       [2.41051863, 1.68005844, 3.94448503, 2.92184076],
       [3.36011687, 6.9393718 , 4.2366691 , 3.43316289],
       [4.52885318, 1.02264427, 5.40540541, 1.02264427]])

Calcula y muestra las siguientes propiedades del array resultante

In [13]:
print("Array:\n", array_bidimensional)
print("Dimensiones (ndim):", array_bidimensional.ndim)
print("Forma (shape):", array_bidimensional.shape)
print("Tamaño total (size):", array_bidimensional.size)
print("Tipo de datos (dtype):", array_bidimensional.dtype)

Array:
 [[2.7027027  2.41051863 6.79327977 6.50109569]
 [2.41051863 1.68005844 3.94448503 2.92184076]
 [3.36011687 6.9393718  4.2366691  3.43316289]
 [4.52885318 1.02264427 5.40540541 1.02264427]]
Dimensiones (ndim): 2
Forma (shape): (4, 4)
Tamaño total (size): 16
Tipo de datos (dtype): float64


#Pregunta 3
Crea un array x que contenga 100 valores equiespaciados entre-10 y 10.

In [15]:
array_equiespaciado = np.linspace(-10, 10, 100)
array_equiespaciado

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x

In [16]:
valor_funcion = np.exp(-array_equiespaciado**2)
valor_funcion

array([3.72007598e-44, 2.03026390e-42, 1.02118442e-40, 4.73376699e-39,
       2.02236984e-37, 7.96279046e-36, 2.88948872e-34, 9.66335032e-33,
       2.97841666e-31, 8.46046409e-30, 2.21489900e-28, 5.34397817e-27,
       1.18830091e-25, 2.43522554e-24, 4.59941880e-23, 8.00603952e-22,
       1.28435035e-20, 1.89889213e-19, 2.58742690e-18, 3.24927813e-17,
       3.76059612e-16, 4.01122945e-15, 3.94320471e-14, 3.57249927e-13,
       2.98295005e-12, 2.29546576e-11, 1.62797100e-10, 1.06407812e-09,
       6.40990174e-09, 3.55860870e-08, 1.82079103e-07, 8.58600196e-07,
       3.73140910e-06, 1.49453385e-05, 5.51683065e-05, 1.87682835e-04,
       5.88451217e-04, 1.70038545e-03, 4.52830117e-03, 1.11140983e-02,
       2.51399360e-02, 5.24089078e-02, 1.00692485e-01, 1.78295348e-01,
       2.90960459e-01, 4.37601640e-01, 6.06561603e-01, 7.74857597e-01,
       9.12262625e-01, 9.89848834e-01, 9.89848834e-01, 9.12262625e-01,
       7.74857597e-01, 6.06561603e-01, 4.37601640e-01, 2.90960459e-01,
      

Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren

In [26]:
valor_maximo = np.max(valor_funcion)
valor_minimo = np.min(valor_funcion)
posicion_maximo = np.unravel_index(np.argmax(valor_funcion),valor_funcion.shape)
posicion_minimo = np.unravel_index(np.argmin(valor_funcion),valor_funcion.shape)

print("Valor máximo:", valor_maximo)
print("Posición del valor máximo:", posicion_maximo)
print("Valor mínimo:", valor_minimo)
print("Posición del valor mínimo:", posicion_minimo)

Valor máximo: 0.9898488339361309
Posición del valor máximo: (49,)
Valor mínimo: 3.720075976020836e-44
Posición del valor mínimo: (0,)


#Pregunta 4


In [35]:
array_original = np.arange(1, 101).reshape(10, 10)
print(array_original)

[[  1   2  -1   4   5   6   7   8  -1  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ -1  22  23  24  25  26  -1  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  -1  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  -1  64  65  66  67  68  -1  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ -1  82  83  84  85  86  -1  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


 Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
 columnas con índices 0, 2, 4, 6, 8)

In [36]:
nuevo_array = array_original[::2, ::2]
nuevo_array

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

Reemplaza todos los elementos que son múltiplos de 3 por-1

In [37]:
if np.any(nuevo_array % 3 == 0):
  nuevo_array[nuevo_array % 3 == 0] = -1
nuevo_array

array([[ 1, -1,  5,  7, -1],
       [-1, 23, 25, -1, 29],
       [41, 43, -1, 47, 49],
       [61, -1, 65, 67, -1],
       [-1, 83, 85, -1, 89]])

Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array
 con estos valores

In [48]:
def es_primo(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

array_primos = array_original[np.vectorize(es_primo)(array_original)]
array_primos

array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

#Pregunta 5
Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.

In [46]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)
print(array1)
print(array2)
print(array3)

[0.36233294 0.01784571 0.96679606 0.4655367  0.38932105]
[0.23859532 0.72963558 0.29925118 0.16275434 0.944119  ]
[0.92043496 0.3756425  0.25185521 0.17149677 0.00987054]


Combina estos arrays para formar una matriz de forma (5, 3)

In [47]:
matriz = np.column_stack((array1, array2, array3))
matriz

array([[0.36233294, 0.23859532, 0.92043496],
       [0.01784571, 0.72963558, 0.3756425 ],
       [0.96679606, 0.29925118, 0.25185521],
       [0.4655367 , 0.16275434, 0.17149677],
       [0.38932105, 0.944119  , 0.00987054]])

 Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4)

In [49]:
nueva_matriz = np.column_stack((np.ones((5, 1)), matriz))
nueva_matriz

array([[1.        , 0.36233294, 0.23859532, 0.92043496],
       [1.        , 0.01784571, 0.72963558, 0.3756425 ],
       [1.        , 0.96679606, 0.29925118, 0.25185521],
       [1.        , 0.4655367 , 0.16275434, 0.17149677],
       [1.        , 0.38932105, 0.944119  , 0.00987054]])

Reordena las columnas de la matriz para que la columna de unos esté al final

In [52]:
matriz_ordenada = nueva_matriz[:, [1, 2, 3, 0]]
matriz_ordenada

array([[0.36233294, 0.23859532, 0.92043496, 1.        ],
       [0.01784571, 0.72963558, 0.3756425 , 1.        ],
       [0.96679606, 0.29925118, 0.25185521, 1.        ],
       [0.4655367 , 0.16275434, 0.17149677, 1.        ],
       [0.38932105, 0.944119  , 0.00987054, 1.        ]])

#Pregunta 6
Crea una matriz simétrica positiva definida de tamaño 3x3.

In [54]:
matriz_simetrica = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])
matriz_simetrica

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [56]:
valores_propios, vectores_propios = np.linalg.eig(matriz_simetrica)
print("Valores propios:", valores_propios)
print("Vectores propios:\n", vectores_propios)

Valores propios: [11.34481428 -0.51572947  0.17091519]
Vectores propios:
 [[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]


Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor
 correspondiente por el vector propio

In [111]:
vector_propio = vectores_propios[:, 0]
valor_propio = valores_propios[0]

resultado_1 = np.dot(matriz_simetrica, vector_propio)
resultado_2 = valor_propio * vector_propio

print(resultado_1)
print(resultado_2)

[-3.72093206 -6.70488789 -8.36085845]
[-3.72093206 -6.70488789 -8.36085845]


#Pregunta 7
 Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de
 coeficientes es singular (no invertible).

In [73]:
A = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
B = np.array([5, 6, -4])

determinante = np.linalg.det(A)
print("Determinante:", determinante)

Determinante: 0.0


In [75]:
solution = np.linalg.solve(A, B)
print("Solución del sistema:", solution)

#No se resuelve porque el determinante es 0, la matriz de coeficientes no tiene inversa.

LinAlgError: Singular matrix

#Pregunta 8
Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.

In [76]:
array_aleatorio = np.random.randint(0, 101, size=(4, 4, 4))
array_aleatorio

array([[[ 60,   7,  87,  24],
        [ 54,  84,  39,  51],
        [ 48,  36,  28, 100],
        [ 28,  85,  55,  75]],

       [[ 43,  70,  92,   4],
        [ 45,  10,  45,  88],
        [ 89,  65,  95,  43],
        [  5,  16,  22,  20]],

       [[ 98,  94,  87,  14],
        [ 77,  96,  17,  69],
        [ 68,  41,   4,  99],
        [ 36,  45,  12,  61]],

       [[ 65,  63,  32,  88],
        [ 15,   2,  68,  75],
        [ 75,  79,  36,   0],
        [  5,  28,  21,  66]]])

Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).

In [77]:
suma_eje_0 = np.sum(array_aleatorio, axis=0)
suma_eje_0

array([[266, 234, 298, 130],
       [191, 192, 169, 283],
       [280, 221, 163, 242],
       [ 74, 174, 110, 222]])

 Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).

In [78]:
promedio_eje_1 = np.mean(array_aleatorio, axis=1)
promedio_eje_1

array([[47.5 , 53.  , 52.25, 62.5 ],
       [45.5 , 40.25, 63.5 , 38.75],
       [69.75, 69.  , 30.  , 60.75],
       [40.  , 43.  , 39.25, 57.25]])

Reestructura el array original en una nueva forma de (8, 8) sin perder datos.

In [79]:
nuevo_array = array_aleatorio.reshape(8, 8)
nuevo_array

array([[ 60,   7,  87,  24,  54,  84,  39,  51],
       [ 48,  36,  28, 100,  28,  85,  55,  75],
       [ 43,  70,  92,   4,  45,  10,  45,  88],
       [ 89,  65,  95,  43,   5,  16,  22,  20],
       [ 98,  94,  87,  14,  77,  96,  17,  69],
       [ 68,  41,   4,  99,  36,  45,  12,  61],
       [ 65,  63,  32,  88,  15,   2,  68,  75],
       [ 75,  79,  36,   0,   5,  28,  21,  66]])

#Pregunta9
 Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles
 explícitos.

In [96]:
array_factorial10 = np.array([np.math.factorial(i) for i in range(10)])
array_factorial10

<ipython-input-96-5756d83c2105>:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  array_factorial10 = np.array([np.math.factorial(i) for i in range(10)])


array([     1,      1,      2,      6,     24,    120,    720,   5040,
        40320, 362880])

 Calcula la suma de todos los elementos del array creado

In [97]:
suma_array = np.sum(array_factorial10)
suma_array

409114

Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para
 manejar enteros arbitrariamente grandes y recalcula la suma.

In [100]:
#suma_array.astype(object)
suma_array_object = np.sum(array_factorial10.astype(object))
suma_array_object


409114

#Pregunta 10
Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución
 normal con media 170 y desviación estándar 10.

In [101]:
matriz_altura = np.random.normal(170, 10, size=(500, 1))
matriz_altura

array([[154.59489956],
       [150.58701489],
       [166.01847844],
       [180.76566185],
       [177.1190574 ],
       [176.10459774],
       [187.51999269],
       [182.69198539],
       [176.52187631],
       [179.61457998],
       [181.92562608],
       [164.86756059],
       [159.25028764],
       [174.62259449],
       [172.47373249],
       [155.59931463],
       [168.17244752],
       [199.07217557],
       [166.45968152],
       [177.76401553],
       [163.82599808],
       [166.13404732],
       [163.18936468],
       [180.61458002],
       [172.94734429],
       [162.46429545],
       [174.73987304],
       [165.85941304],
       [163.80022777],
       [161.6057987 ],
       [182.70519438],
       [167.05863342],
       [189.9803169 ],
       [164.50552742],
       [178.55339431],
       [165.05753635],
       [170.82871069],
       [173.2900305 ],
       [163.54523771],
       [155.80267468],
       [171.34431037],
       [198.0849112 ],
       [145.97306906],
       [180

Calcula el histograma de los datos utilizando 10 bins y muestra los valores de las frecuencias

In [104]:
histograma, bins = np.histogram(matriz_altura, bins=10)
print("Frecuencia:", histograma)

Frecuencia: [  4  18  41  85 124 125  70  23   5   5]


Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.

In [106]:
personas_mas_180 = np.sum(matriz_altura > 180)
personas_menos_160 = np.sum(matriz_altura < 160)

print(personas_mas_180)
print(personas_menos_160)

79
80


 Normaliza los datos de altura para que tengan media 0 y desviación estándar 1

In [107]:
altura_normalizada = (matriz_altura - np.mean(matriz_altura)) / np.std(matriz_altura)
altura_normalizada

array([[-1.51722135e+00],
       [-1.90678919e+00],
       [-4.06845332e-01],
       [ 1.02658625e+00],
       [ 6.72134973e-01],
       [ 5.73529126e-01],
       [ 1.68310966e+00],
       [ 1.21382560e+00],
       [ 6.14088754e-01],
       [ 9.14700673e-01],
       [ 1.13933519e+00],
       [-5.18714965e-01],
       [-1.06471594e+00],
       [ 4.29477871e-01],
       [ 2.20607706e-01],
       [-1.41959184e+00],
       [-1.97478755e-01],
       [ 2.80598603e+00],
       [-3.63960233e-01],
       [ 7.34825138e-01],
       [-6.19955219e-01],
       [-3.95611995e-01],
       [-6.81836217e-01],
       [ 1.01190104e+00],
       [ 2.66642944e-01],
       [-7.52313210e-01],
       [ 4.40877389e-01],
       [-4.22306547e-01],
       [-6.22460103e-01],
       [-8.35759405e-01],
       [ 1.21510952e+00],
       [-3.05741891e-01],
       [ 1.92225407e+00],
       [-5.53904721e-01],
       [ 8.11553041e-01],
       [-5.00249253e-01],
       [ 6.07109890e-02],
       [ 2.99952168e-01],
       [-6.4