<a href="https://colab.research.google.com/github/hvu88/Programacion_101/blob/Parte2/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [12]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [6]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))
print(f'Edad: {persona.get("edad")}')


Nombre: Ana
Ciudad: Lima
Edad: 30


In [8]:
# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)

lista_key = list(persona.keys())
lsta_value = list(persona.values())
print(lista_key)
print(lsta_value)
print(tuple(zip(lista_key,lsta_value)))
print(dict(zip(lista_key,lsta_value)))

value_key = dict(zip(lista_key,lsta_value))
print(value_key)



{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}
['nombre', 'edad', 'ciudad', 'profesion']
['Ana', 30, 'Lima', 'Ingeniera']
(('nombre', 'Ana'), ('edad', 30), ('ciudad', 'Lima'), ('profesion', 'Ingeniera'))
{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}
{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}


In [11]:
list(persona.items())

[('nombre', 'Ana'),
 ('edad', 30),
 ('ciudad', 'Lima'),
 ('profesion', 'Ingeniera')]

In [30]:
print([ {k:v} for k,v in persona.items()])
print(0dict(persona.items()))

[{'nombre': 'Ana'}, {'edad': 30}]
{'nombre': 'Ana', 'edad': 30}


In [22]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'nombre': 'Ana', 'edad': 30}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [23]:
# Obtener todas las claves
print(persona.keys())




dict_keys(['nombre', 'edad'])


In [24]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30])


In [25]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


La clave 'edad' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [28]:
dic_auto = {'marca': 'Toyota', 'modelo': 'Corolla', 'año': 2022, 'color': 'Rojo'}
atributo = input("Ingresa un atributo (marca, modelo, año): ")
print(f'{atributo}: {dic_auto[atributo]} \n')
dic_auto['precio'] = 25_000
del dic_auto['color']
print(f'Información automovil')
for key,value in dic_auto.items():
  print(f'{key}: {value}')

Ingresa un atributo (marca, modelo, año): marca
marca: Toyota 

Información automovil
marca: Toyota
modelo: Corolla
año: 2022
precio: 25000


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [ ]:
# Crear un set
numeros = {1, 2,2,2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [ ]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [ ]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 2, 4, 5, 6, 7}


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [ ]:
uno_diez = {1,2,3,4,5,6,7,8,9,10}
cinco_quince = set(range(5,16))

print(f'Intesección: {uno_diez.intersection(cinco_quince)}')
print(f'Unión: {uno_diez.union(cinco_quince)} \n')

uno_diez.remove(1)
print(uno_diez)

set_amigos = {'Pedro', 'Jose', 'Carlos'}
print(set_amigos)

Intesección: {5, 6, 7, 8, 9, 10}
Unión: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15} 

{2, 3, 4, 5, 6, 7, 8, 9, 10}
{'Pedro', 'Carlos', 'Jose'}


## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [32]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [33]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


Elemento en [1][1]: 5


In [ ]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [37]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f'{matriz_np} \n')

print(matriz_np.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(3, 3)


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [41]:
iden = np.identity(4)
zeros = np.zeros((4,4))
ones = np.ones((4,4))

print(f'{iden} \n')
print(f'{zeros} \n')
print(f'{ones} \n')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



In [46]:
np.random.randint(0,10,(4,4))

array([[4, 9, 1, 8],
       [3, 4, 8, 8],
       [7, 2, 6, 2],
       [7, 1, 0, 6]])

In [52]:
random_matriz=np.random.rand(3,2,1,2)
print(random_matriz)
print(random_matriz.shape)

[[[[2.84076340e-01 7.59430109e-01]]

  [[5.62685874e-01 1.25089875e-04]]]


 [[[2.95208566e-01 7.56445298e-01]]

  [[7.83705404e-01 5.62314611e-01]]]


 [[[7.61894933e-01 9.43242812e-01]]

  [[7.27208851e-01 1.68516693e-01]]]]
(3, 2, 1, 2)


In [70]:
matriz4 = np.random.randint(0,10,(4,4))
print(matriz4.shape)
print(matriz4)
print(np.linalg.inv(matriz4))
print(np.linalg.det(matriz4))
print(np.trace(matriz4))
print(np.transpose(matriz4))

(4, 4)
[[4 3 0 7]
 [6 8 7 7]
 [8 6 2 5]
 [8 3 8 8]]
[[-0.08531746 -0.1468254   0.19907407  0.0787037 ]
 [-0.01587302  0.15873016  0.03703704 -0.14814815]
 [-0.10714286  0.07142857 -0.08333333  0.08333333]
 [ 0.1984127   0.01587302 -0.12962963  0.01851852]]
1511.9999999999993
22
[[4 6 8 8]
 [3 8 6 3]
 [0 7 2 8]
 [7 7 5 8]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [127]:
import math
import random

matriz3 = []

for i in range(3):
  fila = []
  for j in range(3):
    fila.append(random.randint(0,10))
  matriz3.append(fila)

print(matriz3)

matriz3[1][1] = 100
print(matriz3)
print('')
matriz4 = np.random.randint(0,10,(4,4))
print(matriz4)
print('')
print(matriz4 + 5)
print('')
print(matriz4 * 2)


[[5, 5, 6], [3, 0, 8], [0, 5, 5]]
[[5, 5, 6], [3, 100, 8], [0, 5, 5]]

[[2 0 3 6]
 [0 9 9 0]
 [7 9 8 0]
 [8 1 4 4]]

[[ 7  5  8 11]
 [ 5 14 14  5]
 [12 14 13  5]
 [13  6  9  9]]

[[ 4  0  6 12]
 [ 0 18 18  0]
 [14 18 16  0]
 [16  2  8  8]]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [ ]:
telefonos = [100,200,300,400,500]
laptops = [1000,2000,3000,4000,5000]
tablets = [10,20,30,40,50]

print(f'Ultimos 3 dias')
print(f'Telefonos: {telefonos[-3:]}')


Ultimos 3 dias
Telefonos: [300, 400, 500]


---

# Gracias por completar este laboratorio!

---